# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-10 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_axf_mainshow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Axf_mainshow',
            new_name='AxfMainshow',
        ),
    ]
